name: Update SquishPass
on:
  repository_dispatch:
    types: [update_squishpass]
  workflow_dispatch:
    inputs:
      points:
        description: 'Manual Point Entry'
        required: true
        default: '0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Update
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          POINTS: ${{ github.event.client_payload.points || github.event.inputs.points }}
        run: node squishpass.mjs

      - name: Save Persistence
        run: |
          git config --global user.name 'SquishBot'
          git config --global user.email 'bot@github.com'
          git pull origin main
          git add last_post_data.json
          git commit -m "Update persistence [skip ci]" || echo "No changes"
          git push
